version: '3'

services:
  minha-aplicacao:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "5000:500"  # Mapeamento de portas se necessário
    # Outras configurações da sua aplicação

  minha-aplicacao-worker:
    build:
      context: ./chatbot
      dockerfile: Dockerfile.worker
    # Outras configurações da sua aplicação worker
