version: '3'

services:
  maturador:
    build:
      context: .
      dockerfile: Dockerfile1
    ports:
      - "5000:5000"  # Mapeamento de portas se necessário
    # Outras configurações da sua aplicação

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    # Outras configurações da sua aplicação worker
  maturador2:
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - "5002:5002"  # Mapeamento de portas se necessário
    # Outras configurações da sua aplicação

  worker2:
    build:
      context: .
      dockerfile: Dockerfile.worker2
    # Outras configurações da sua aplicação worker
  maturador3:
    build:
      context: .
      dockerfile: Dockerfile3
    ports:
      - "5004:5004"  # Mapeamento de portas se necessário
    # Outras configurações da sua aplicação

  worker3:
    build:
      context: .
      dockerfile: Dockerfile.worker3
    # Outras configurações da sua aplicação worker
  maturador4:
    build:
      context: .
      dockerfile: Dockerfile4
    ports:
      - "5006:5004"  # Mapeamento de portas se necessário
    # Outras configurações da sua aplicação

  worker4:
    build:
      context: .
      dockerfile: Dockerfile.worker4
