version: '3'

services:
  maturador:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Mapeamento de portas se necessário
    # Outras configurações da sua aplicação

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    # Outras configurações da sua aplicação worker
